# Life Expectancy Change in US Prisons during the COVID-19 pandemic

The increased burden of COVID-19 infection and mortality for those incarcerated in the United States has been well documented. A recent study found that over the first 52 weeks of the COVID-19 pandemic, people in US prisons were 3.3 and 2.5 times more likely than the overall US population to have a reported case and die of COVID-19 respectively. The impact that this has had on overall mortality in terms of increases in the number of deaths observed in previous years, however, is not well known. Several studies have focused on specific prison systems pointing to increases in year to year mortality observed in [2020 from previous years](https://www.npr.org/2022/03/07/1083983516/as-covid-spread-in-federal-prisons-many-at-risk-inmates-tried-and-failed-to-get-) and the contribution COVID has had on [declining life expectancy](https://www.ajpmonline.org/article/S0749-3797(22)00045-9/fulltext), however how the impact across the whole of US prisons is not yet known.

Traditionally, the Bureau of Justice Statistics (BJS) reports information on mortality rates across the whole of prison systems in annual cycles. The information reported includes cause and age specific breakdowns of mortality rates for those incarcerated in state and federal prisons however the report is not without several notable limitations. First, annual reports made by the BJS are often delayed by several years making it difficult to respond to current health issues using the report. Second, the report relies on single point in time estimates of the prison population across the year to calculate rates, assuming that the population on December 31st is indicative of the yearly population. During 2020 and 2021, however, population counts greatly changed over time and using a single point in time estimate for the population may not accurately portray the mortality risk experienced during this time period. Third, while the BJS reports information on causes and age specific mortality it has, historically, not reported on the cross section of these two measures, making it difficult to assess the impact COVID-19 has had on changes in mortality rate as has been done in previous studies.

To overcome the limitations mentioned above we our team has collected mortality and population data from state and federal prisons from the years 2015 forward in order to make a detailed comparative analysis of the impact that COVID-19 has had on populations in prisons in the United States. Our end goal is to report how annual mortality rates changed in US prisons during the pandemic in terms of life expectancy and how much of this decline was due specifically to COVID. To do such an analysis would traditionally require uniform and temporally granular data on age specific mortality and populations across the whole of US prison systems. Such data, however, is extremely difficult to obtain as prison system are independently managed by states in the US and as such their data collection and reporting system greatly differ. Specifically the frequency which prison systems report data and the age groups which they report data for greatly differ from state to state. To overcome this limitation our team will rely on [harmonizing techniques](https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1002687) used when data on age-specific mortality data is not available but is a desired metric, such as in this case. 